spring.application.name=LeetcodeBox
server.port=8080

#groq api setup
Groq.api.url=https://api.groq.com/openai/v1/chat/completions
Groq.api.key=${GROQ_API_KEY}
#db setup
spring.datasource.url=jdbc:mysql://localhost:3306/leetcodebox
spring.datasource.username=root
spring.datasource.password=Prahar@08
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#loggings
logging.file.name=logs/app.log
logging.level.Service=INFO
logging.level.Controller=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
