spring.application.name=LeetcodeBox
server.port=8080

#db setup
spring.datasource.url=jdbc:mysql://localhost:3306/leetcodebox
spring.datasource.username=root
spring.datasource.password=Prahar@08
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
